version: "3.9"
   
services:
  db:
    image: postgres:12-alpine
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: community_db
    volumes:
      - community_db_data:/var/lib/postgresql/data
    networks:
        - app

  community_api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: bash -c "cd api && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app

volumes:
    community_db_data:

networks:
  app:
    driver: bridge
