name: API

on:
  push:
    paths:
      - "api/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r api/requirements.txt

    - name: Run linting
      run: |
        export DJANGO_SETTINGS_MODULE=api.settings.test
        black . --check

    - name: Run migrations
      run: |
        export DJANGO_SETTINGS_MODULE=api.settings.test
        python api/manage.py migrate

    - name: Run tests
      run: |
        export DJANGO_SETTINGS_MODULE=api.settings.test
        python api/manage.py test
