name: Build Docker Images

on:
  push:
    branches:
      - "master"

jobs:
  build-client-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_NEXT_PUBLIC_USE_API: true
          envkey_NEXT_PUBLIC_API_URL: "https://api.merged.carletoncomputerscience.ca"
      - name: Move env file
        run: |
          mv .env ./client/.env.local
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: client
          file: client/Dockerfile.prod
          push: true
          tags: |
            ghcr.io/carletoncomputersciencesociety/merged/merged-client:latest

  build-api-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      - name: Move env file
        run: |
          mv .env ./api/
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: api
          file: api/Dockerfile.prod
          push: true
          tags: |
            ghcr.io/carletoncomputersciencesociety/merged/merged-api:latest
