name: Client

on:
  push:
    paths:
      - "client/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: |
          cd client
          yarn
      - name: Run Jest
        run: |
          cd client
          yarn run test
